In [6]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [8]:
df = pd.read_csv('/content/drive/MyDrive/messi barca.csv', encoding='latin1')

In [9]:
df.head()

,Season,Age,Competition,Matches Played,Starts,Minutes played,Goals scored,Assists,PK,PKatt,CrdY,CrdR,Goal/90,Ast/90,G+A/90,G-PK/90,G+A-PK/90
0,2004-2005,17,Champions League,1,1,90,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00
1,2004-2005,17,La Liga,7,0,70,1,0,0,0,0,0,1.29,0.00,1.29,1.29,1.29
2,2005-2006,18,Champions League,6,4,322,1,1,0,0,0,0,0.28,0.28,0.56,0.28,0.56
3,2005-2006,18,La Liga,17,11,911,6,3,0,0,2,0,0.59,0.30,0.89,0.59,0.89
4,2006-2007,19,Champions League,5,4,385,1,0,0,0,1,0,0.23,0.00,0.23,0.23,0.23

In [10]:
print("Розмірність:", df.shape)

Розмірність: (44, 17)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Season          44 non-null     object
 1   Age             44 non-null     int64
 2   Competition     44 non-null     object
 3   Matches Played  44 non-null     int64
 4   Starts          44 non-null     int64
 5   Minutes played  44 non-null     int64
 6   Goals scored    44 non-null     int64
 7   Assists         44 non-null     int64
 8   PK              44 non-null     int64
 9   PKatt           44 non-null     int64
 10  CrdY            44 non-null     int64
 11  CrdR            44 non-null     int64
 12  Goal/90         44 non-null     float64
 13  Ast/90          44 non-null     float64
 14  G+A/90          44 non-null     float64
 15  G-PK/90         44 non-null     float64
 16  G+A-PK/90       44 non-null     float64
dtypes: float64(5), int64(10), object(2)
memory usage: 6.0+ KB

In [12]:
df.describe()

,Age,Matches Played,Starts,Minutes played,Goals scored,Assists,PK,PKatt,CrdY,CrdR,Goal/90,Ast/90,G+A/90,G-PK/90,G+A-PK/90
count,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.000000,44.0,44.000000,44.000000,44.000000,44.000000,44.000000
mean,25.886364,15.159091,13.636364,1237.068182,13.386364,5.431818,1.659091,2.022727,1.500000,0.0,0.847727,0.351591,1.199318,0.756591,1.107727
std,4.666635,12.860510,11.941896,1084.253326,14.203203,5.903872,2.322220,2.663174,1.562645,0.0,0.361713,0.261924,0.424485,0.344235,0.414268
min,17.000000,1.000000,0.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,22.000000,5.750000,4.000000,387.250000,2.750000,1.000000,0.000000,0.000000,0.000000,0.0,0.677500,0.200000,0.997500,0.612500,0.867500
50%,27.000000,10.000000,9.000000,818.000000,8.000000,3.000000,1.000000,1.000000,1.000000,0.0,0.860000,0.365000,1.290000,0.760000,1.185000
75%,30.000000,31.000000,27.250000,2504.750000,23.500000,9.500000,3.000000,4.000000,2.000000,0.0,1.102500,0.482500,1.470000,0.992500,1.375000
max,32.000000,38.000000,37.000000,3375.000000,50.000000,20.000000,10.000000,11.000000,6.000000,0.0,1.560000,1.000000,1.940000,1.500000,1.870000

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print("Масив:", arr)
print("Тип елементів:", arr.dtype)
print("Форма масиву:", arr.shape)

arr2 = arr * 2
arr3 = arr + 5
print("Помножений масив:", arr2)
print("Масив після додавання 5:", arr3)

print("Сума:", arr.sum())
print("Середнє:", arr.mean())
print("Мінімум:", arr.min())
print("Максимум:", arr.max())

Масив: [10 20 30 40 50]
Тип елементів: int64
Форма масиву: (5,)
Помножений масив: [ 20  40  60  80 100]
Масив після додавання 5: [15 25 35 45 55]
Сума: 150
Середнє: 30.0
Мінімум: 10
Максимум: 50